CREATE TABLE Volunteer ( 
VolunteerID      INTEGER IDENTITY (1,1)     NOT NULL UNIQUE, 
FirstName     NVARCHAR(35) NOT NULL, 
LastName     NVARCHAR(35) NOT NULL, 
StreetAddress 	NVARCHAR(50) NULL, 
City		NVARCHAR(35) NULL, 
States		NVARCHAR(35) NULL,
ZipCode		NVARCHAR(10) 	NULL,
County	NVARCHAR(35)	NULL,
CellPhoneNumber    NVARCHAR(14) NULL,     
HomePhoneNumber    NVARCHAR(14) NULL,     
WorkPhoneNumber    NVARCHAR(14) NULL, 
Email  		NVARCHAR(50) NULL,    
Birthday	date NULL,
Gender	NVARCHAR(10) NULL,
CompanyName		NVARCHAR(50) NULL,
Position	NVARCHAR(20) NULL,
CompanyAddress	NVARCHAR(50) NULL,
DateOrientation		date NULL, 
DateStarted		date NULL, 
HoursPerMonth		INTEGER NULL,
VolunteerPosition	NVARCHAR(20) NULL,
AreaOfInterest NVARCHAR(20) NULL,
Skills NVARCHAR(20) NULL,
Donor NVARCHAR(1) NULL,
Board NVARCHAR(1) NULL,
EmailList NVARCHAR(1) NULL,
MailList NVARCHAR(1) NULL,

PRIMARY KEY (VolunteerID))