CREATE TABLE Volunteer ( 
VolunteerID      INTEGER IDENTITY (1,1)     NOT NULL UNIQUE, 
FirstName     VARCHAR(35) NOT NULL, 
LastName     VARCHAR(35) NOT NULL, 
StreetAddress 	VARCHAR(50) NULL, 
City		VARCHAR(35) NULL, 
States		VARCHAR(35) NULL,
ZipCode		CHAR(10) 	NULL,
County	VARCHAR(35)	NULL,
CellPhoneNumber    CHAR(10) NULL,     
HomePhoneNumber    CHAR(10) NULL,     
WorkPhoneNumber    CHAR(10) NULL, 
Email  		VARCHAR(50) NULL,    
Birthday	CHAR(15)		NULL,
Gender	VARCHAR(10) NULL,
Job		VARCHAR(50) NULL,
DateOrientation		CHAR(15) NULL, 
DateStarted		CHAR(15) NULL, 
HoursPerMonth		INTEGER NULL,
CompanyName		VARCHAR(50) NULL,
Position	VARCHAR(20) NULL,
CompanyAddress	VARCHAR(50) NULL,
VolunteerPosition	VARCHAR(20) NULL,
AreaOfInterest VARCHAR(20) NULL,
Skills VARCHAR(20) NULL,
Donor VARCHAR(3) NULL,
Board VARCHAR(3) NULL,
EmailList VARCHAR(3) NULL,
MailList VARCHAR(3) NULL,

PRIMARY KEY (VolunteerID))